version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    network_mode: host
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./etc-mosquitto:/etc/mosquitto
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
