version: '2'
services:
  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    privileged: true
    network_mode: host
    volumes:
      - ./config:/config
    devices:
      - "/dev/ttyUSB0:/zwavestick:rwm"
      - "/dev/ttyUSB1:/zigbeestick:rwm"
    restart: unless-stopped
