version: '2'
services:
  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    networks:
      default:
        ipv4_address: 192.168.0.202
    volumes:
      - /var/services/homes/ottobonn/home-assistant/config:/config
    devices:
      - "/dev/ttyUSB1:/zigbeestick:rwm"
    restart: unless-stopped

networks:
  default:
    external:
      name: vlan
